apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: system
  labels:
    app.kubernetes.io/name: squall
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: squall
      app.kubernetes.io/component: proxy
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: squall
        app.kubernetes.io/component: proxy
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: proxy
      containers:
      - name: proxy
        image: proxy:latest
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
