apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: squall
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: kustomize
  name: proxy
  namespace: system
