---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - squall.ackstorm.ai
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - squall.ackstorm.ai
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - squall.ackstorm.ai
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
