apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: squall
    app.kubernetes.io/managed-by: {{ .Release.Service }}
